name: Publish to Curseforge.com
on:
  release:
    types: [created]

jobs:
  publish:
    strategy:
      matrix:
        java: [16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-packages-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-packages-${{ runner.os }}-

      - name: Publish release on Curseforge
        env:
          CURSE_API_KEY: ${{ secrets.CURSE }}
        run: ./gradlew build publish curseforge --stacktrace --no-daemon

      - name: Clean Gradle Cache
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: |
          rm -f  $HOME/.gradle/caches/*/*.lock
          rm -rf $HOME/.gradle/caches/*/plugin-resolution/
          rm -rf $HOME/.gradle/caches/*/scripts/
          rm -rf $HOME/.gradle/caches/*/scripts-remapped/
          rm -rf $HOME/.gradle/caches/*/fileHashes/
          rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
